-- A simple http server
srv=net.createServer(net.TCP) 
srv:listen(80,function(conn) 
	conn:on("receive",function(conn,payload) 
		print(payload) 
		conn:send("<h1> Hello, NodeMcu.</h1></br>")
		conn:send("<h2> Hello, NodeMcu.</h2>")
	end) 
	conn:on("sent",function(conn) conn:close() end)
end)